"A datetime string with format `Y-m-d H:i:s`, e.g. `2018-05-23 13:43:32`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

#"Indicates what fields are available at the top level of a query operation."
#type Query {
#    "Find a single user by an identifying attribute."
#    user(
#      "Search by primary key."
#      id: ID @eq @rules(apply: ["prohibits:email", "required_without:email"])
#
#      "Search by email address."
#      email: String @eq @rules(apply: ["prohibits:id", "required_without:id", "email"])
#    ): User @find
#
#    "List multiple users."
#    users(
#      "Filters by name. Accepts SQL LIKE wildcards `%` and `_`."
#      name: String @where(operator: "like")
#    ): [User!]! @paginate(defaultCount: 10)
#}

#"Account of a person who utilizes this application."
#type User {
#    "Unique primary key."
#    id: ID!
#
#    "Non-unique name."
#    name: String!
#
#    "Unique email address."
#    email: String!
#
#    "When the email was verified."
#    email_verified_at: DateTime
#
#    "When the account was created."
#    created_at: DateTime!
#
#    "When the account was last updated."
#    updated_at: DateTime!
#}

"Can be used as an argument to upload files using https://github.com/jaydenseric/graphql-multipart-request-spec"
scalar Upload @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Upload")

type Query

type Mutation

type Response {
  statusCode: Int!
  statusMessage: String!
  errors: String
}

# Query/Mutationの定義.
#import App/Common.graphql
#import App/PersonalSetting.graphql
#import App/Qmart/Qmart.graphql
#import Usecases/Calendar.graphql

# Sample-Query/Mutationの定義.
#import Sample/InputForm.graphql
#import Sample/Pagination.graphql
#import Sample/Redis.graphql
