###########################
# wportal2
# リリース環境用

services:
  ###################################
  # wportal_web : php + Apacheサーバー
  service_container_web:
    image: 979109089196.dkr.ecr.ap-northeast-1.amazonaws.com/wportal2_ecr_service_container:latest
    container_name: service_container_web
    build:
      context: .
      dockerfile: DockerfileForServiceContainer
    environment:
      - APP_TIMEOUT=60
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_UPLOAD=20M
    working_dir: /var/www/html/wportal2-app
    ports:
      - "80:80"
    networks:
      - service_container_net
    #volumes:
    #  - ./:/var/www/html

networks:
  service_container_net:
    driver: bridge