# App/Common.graphql
extend type Query @guard {
  # ユーザー一覧の取得.
  AppTrnUserList: [AppTrnUser]! @field(
    resolver: "App\\GraphQL\\App\\Queries\\AppTrnUserListQuery"
  )

  # 部署一覧の取得.
  AppTrnDivisionList: [AppTrnDivision]! @field(
    resolver: "App\\GraphQL\\App\\Queries\\AppTrnDivisionListQuery"
  )

  # プロジェクト一覧の取得.
  AppTrnProjectList: [AppTrnProject]! @field(
    resolver: "App\\GraphQL\\App\\Queries\\AppTrnProjectListQuery"
  )
}

type AppTrnUser {
  id: Int!
  authId: Int!
  nickname: String
  faceImagePath: String
}

type AppTrnDivision {
  id: Int!
  name: String
}

type AppTrnProject {
  id: Int!
  name: String
}
